### ISSUE TITLE
publish error - You will need to access the Chrome Web Store Developer Dashboard and publish manually.

### ISSUE THREAD

**Issue by ShahafShavit** [mnao305/chrome-extension-upload#28]
![Image](https://github.com/user-attachments/assets/4fae0e26-2071-44b9-bec6-9bf3cfe2d8b2)

no deep logging to work with really and find out what failed...
FYI, first time running this, never tried before.

**Comment by aayusharyan** [comment]
Same. Facing same issue.

**Comment by ShahafShavit** [comment]
> Same. Facing same issue.

fixed the issue by trying and testing:
if you are trying to publish to testers using the example in the examples you will get here.
anyway, here's my solution settings.
```
      - name: Upload and Publish to Chrome Web Store
        uses: mnao305/chrome-extension-upload@v5.0.0
        with: 
            file-path: extension.zip
            extension-id: ${{ secrets.CHROME_EXTENSION_ID }}

            client-id: ${{ secrets.CHROME_CLIENT_ID }}
            client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
            refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
            publish: true
            publish-target: trustedTesters
```
this one is working for me.
i had to add `publish: true` to the settings, `publish-target: trustedTesters` is not enough.
